# Generated by Django 5.0.3 on 2024-03-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_cadastrolojas_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrolojas',
            name='cd',
            field=models.CharField(max_length=13),
        ),
    ]
