# Generated by Django 5.0.3 on 2024-03-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0004_rename_cadastrolojas_cadastroloja'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastroLoja',
            new_name='cadastroLojas',
        ),
    ]
