# Generated by Django 5.0.3 on 2024-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0006_cadastrolojas_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrolojas',
            name='categoria',
            field=models.CharField(choices=[('CD', 'CD'), ('LOJA', 'Loja'), ('LOJA | CD', 'Loja | CD')], default='', max_length=100),
        ),
    ]
