# Generated by Django 5.0.3 on 2024-03-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0014_alter_cadastrocameras_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocameras',
            name='vnc',
        ),
    ]
