# Generated by Django 5.0.3 on 2024-04-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0016_alter_cadastrocameras_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('loja', models.CharField(max_length=5)),
                ('ip_etiqueta', models.CharField(max_length=20)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
