# Generated by Django 5.0.3 on 2024-04-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0017_cadastroetiqueta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastroEtiqueta',
            new_name='cadastroEtiquetas',
        ),
    ]
