# Generated by Django 5.0.3 on 2024-04-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0018_rename_cadastroetiqueta_cadastroetiquetas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cadastroEtiquetas',
        ),
    ]
