# Generated by Django 5.0.3 on 2024-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0019_delete_cadastroetiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrolojas',
            name='codigo_omni',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
