# Generated by Django 5.0.3 on 2024-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0020_cadastrolojas_codigo_omni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrolojas',
            name='descricao_omni',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
