# Generated by Django 5.0.3 on 2024-05-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0022_remove_cadastrolojas_descricao_omni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrolojas',
            name='codigo_omni',
        ),
    ]
