# Generated by Django 5.0.3 on 2024-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_alter_status_status_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='titulo',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
