# Generated by Django 5.0.3 on 2024-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroCodigoOmni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descricao', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=150)),
            ],
        ),
    ]
