# Generated by Django 5.0.3 on 2024-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocodigoomni',
            name='acesso',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GESTAO', 'Gestao')], default='', max_length=100),
        ),
    ]
