# Generated by Django 5.0.3 on 2024-03-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroLojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=10)),
                ('loja', models.CharField(max_length=5)),
                ('regiao', models.IntegerField(max_length=10)),
                ('cd', models.CharField(max_length=5)),
                ('localizacao', models.CharField(max_length=150)),
                ('cnpj', models.IntegerField(max_length=14)),
                ('tronco', models.CharField(max_length=50)),
            ],
        ),
    ]
