# Generated by Django 5.0.3 on 2024-03-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrolojas',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
