# Generated by Django 5.0.3 on 2024-03-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_alter_cadastrolojas_cd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastroLojas',
            new_name='cadastroLoja',
        ),
    ]
