# Generated by Django 5.0.3 on 2024-03-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_rename_cadastroloja_cadastrolojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrolojas',
            name='categoria',
            field=models.CharField(choices=[('CD', 'CD'), ('LOJA', 'Loja'), ('LOJACD', 'Loja | CD')], default='', max_length=100),
        ),
    ]
