# Generated by Django 5.0.3 on 2024-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0010_alter_cadastrocameras_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocameras',
            name='vnc',
            field=models.ImageField(blank=True, upload_to='media/camera'),
        ),
    ]
