# Generated by Django 5.0.3 on 2024-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0011_cadastrocameras_vnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocameras',
            name='vnc',
            field=models.FileField(blank=True, upload_to='media/camera'),
        ),
    ]
